# Port for our Python Flask API to run on
PYTHON_API_PORT=8888

# Java API URL for sending LIVE and FINAL counts
JAVA_COUNT_UPDATE_API_URL=http://192.168.0.59:5050/api/send-count

# ==============================================================================
# Camera 1 Configuration (Loader-BC03)
# ==============================================================================
camera_1=rtsp://admin:Amazin@123@192.168.0.64:554/cam/realmonitor?channel=1&subtype=0
loader_name_1=Loader-BC03
relay_ip_1=192.168.0.21
relay_start_cmd_1=*R4#0#$#
relay_stop_cmd_1=*R4#1#$#

# Loader 1 Specific Parameters
confidence_1=0.25
max_age_1=5
min_hits_1=1
iou_threshold_1=0.3
inactivity_limit_1=5.0
max_settle_timeout_1=20.0

# Model for Loader 1 (separate model per belt)
model_path_1=best.pt

# Line Crossing Params for Loader 1
counting_line_y_1=0.55
counting_direction_1=down
center_dot_position_1=0.5


# ==============================================================================
# Camera 2 Configuration (Loader-BC02)
# ==============================================================================
camera_2=rtsp://admin:Amazin@123@192.168.0.65:554/cam/realmonitor?channel=1&subtype=0
loader_name_2=Loader-BC02
relay_ip_2=192.168.0.22
relay_start_cmd_2=*R4#0#$#
relay_stop_cmd_2=*R4#1#$#

# Loader 2 Specific Parameters
confidence_2=0.28
max_age_2=5
min_hits_2=1
iou_threshold_2=0.3
inactivity_limit_2=5.0
max_settle_timeout_2=5.0

# Model for Loader 2 (separate model per belt)
model_path_2=best.pt

# Line Crossing Params for Loader 2
counting_line_y_2=0.5
counting_direction_2=down
center_dot_position_2=0.5


# ==============================================================================
# Shared Relay Configuration
# ==============================================================================
# Port for ALL relay devices
relay_port=5000

# ==============================================================================
# Fallback Model Configuration (optional)
# ==============================================================================
model_path=best.pt
